<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\SystemFramework\SystemFramework.csproj" />
		<ProjectReference Include="..\Database\DatabaseEntities\DatabaseEntities.csproj" />
		<ProjectReference Include="..\Database\MigrationHandler\MigrationHandler.csproj" />
		<ProjectReference Include="..\ServiceInterfaces\BusinessLogicServiceInterface\BusinessLogicServiceInterface.csproj" />
		<ProjectReference Include="..\ServiceInterfaces\DataAccessServiceInterface\DataAccessServiceInterface.csproj" />
		<ProjectReference Include="..\Services\APIGateWay\APIGateWay.csproj" />
		<ProjectReference Include="..\Services\BusinessLogicService\BusinessLogicService.csproj" />
		<ProjectReference Include="..\Services\DataAccessService\DataAccessService.csproj" />
	</ItemGroup>
</Project>
