// <auto-generated />
using System;
using DatabaseEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MigrationHandler.Migrations
{
    [DbContext(typeof(App_DBContext))]
    [Migration("20260612172006_FixBaccaratHandColumnSize")]
    partial class FixBaccaratHandColumnSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseEntities.ErrError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("pk_ERR_Error");

                    b.ToTable("ERR_Error", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Detail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TargetID");

                    b.HasKey("Id")
                        .HasName("pk_LOG_Admin");

                    b.HasIndex(new[] { "AdminId", "CreatedAt" }, "idx_LOG_Admin_Time");

                    b.ToTable("LOG_Admin", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogBaccarat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BankerHand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Bet")
                        .HasColumnType("int");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Net")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlayerHand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerID");

                    b.HasKey("Id")
                        .HasName("pk_LOG_Baccarat");

                    b.HasIndex(new[] { "PlayerId", "CreatedAt" }, "idx_LOG_Baccarat_PlayerTime");

                    b.ToTable("LOG_Baccarat", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogBlackjack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Bet")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("DealerCards")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Net")
                        .HasColumnType("int");

                    b.Property<string>("PlayerCards")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerID");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("pk_LOG_Blackjack");

                    b.HasIndex(new[] { "PlayerId", "CreatedAt" }, "idx_LOG_Blackjack_PlayerTime");

                    b.ToTable("LOG_Blackjack", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogHorse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Bet")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Net")
                        .HasColumnType("int");

                    b.Property<string>("PickedName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerID");

                    b.Property<string>("WinnerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("pk_LOG_Horse");

                    b.HasIndex(new[] { "PlayerId", "CreatedAt" }, "idx_LOG_Horse_PlayerTime");

                    b.ToTable("LOG_Horse", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogRoulette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("Net")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerID");

                    b.Property<int>("TotalBet")
                        .HasColumnType("int");

                    b.Property<string>("WinNum")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id")
                        .HasName("pk_LOG_Roulette");

                    b.HasIndex(new[] { "PlayerId", "CreatedAt" }, "idx_LOG_Roulette_PlayerTime");

                    b.ToTable("LOG_Roulette", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogSpin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Bet")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte>("MachineNum")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerID");

                    b.Property<string>("SpinType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbols")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("WinAmount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_LOG_Spin");

                    b.HasIndex(new[] { "PlayerId", "CreatedAt" }, "idx_LOG_Spin_PlayerTime");

                    b.ToTable("LOG_Spin", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.UsrAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("pk_USR_Admins");

                    b.HasIndex(new[] { "Email" }, "uq_USR_Admins_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "uq_USR_Admins_Username")
                        .IsUnique();

                    b.ToTable("USR_Admins", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.UsrPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime?>("LastBonusAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Player");

                    b.Property<string>("ProfileAvatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfileImageContentType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("ProfileImageUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tokens")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_USR_Players");

                    b.HasIndex(new[] { "Email" }, "uq_USR_Players_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "uq_USR_Players_Name")
                        .IsUnique();

                    b.ToTable("USR_Players", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.UsrSession", b =>
                {
                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerID");

                    b.HasKey("Token")
                        .HasName("pk_USR_Sessions");

                    b.HasIndex(new[] { "PlayerId" }, "idx_USR_Sessions_Player");

                    b.ToTable("USR_Sessions", (string)null);
                });

            modelBuilder.Entity("DatabaseEntities.LogAdmin", b =>
                {
                    b.HasOne("DatabaseEntities.UsrAdmin", "Admin")
                        .WithMany("LogAdmins")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("fk_LOG_Admin_Admin");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("DatabaseEntities.LogBaccarat", b =>
                {
                    b.HasOne("DatabaseEntities.UsrPlayer", "Player")
                        .WithMany("LogBaccarats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_LOG_Baccarat_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseEntities.LogBlackjack", b =>
                {
                    b.HasOne("DatabaseEntities.UsrPlayer", "Player")
                        .WithMany("LogBlackjacks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_LOG_Blackjack_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseEntities.LogHorse", b =>
                {
                    b.HasOne("DatabaseEntities.UsrPlayer", "Player")
                        .WithMany("LogHorses")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_LOG_Horse_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseEntities.LogRoulette", b =>
                {
                    b.HasOne("DatabaseEntities.UsrPlayer", "Player")
                        .WithMany("LogRoulettes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_LOG_Roulette_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseEntities.LogSpin", b =>
                {
                    b.HasOne("DatabaseEntities.UsrPlayer", "Player")
                        .WithMany("LogSpins")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_LOG_Spin_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseEntities.UsrSession", b =>
                {
                    b.HasOne("DatabaseEntities.UsrPlayer", "Player")
                        .WithMany("UsrSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_USR_Sessions_Player");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseEntities.UsrAdmin", b =>
                {
                    b.Navigation("LogAdmins");
                });

            modelBuilder.Entity("DatabaseEntities.UsrPlayer", b =>
                {
                    b.Navigation("LogBaccarats");

                    b.Navigation("LogBlackjacks");

                    b.Navigation("LogHorses");

                    b.Navigation("LogRoulettes");

                    b.Navigation("LogSpins");

                    b.Navigation("UsrSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
