// <auto-generated />
using DatabaseEntities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MigrationHandler.Migrations
{
    [DbContext(typeof(App_DBContext))]
    [Migration("20260603110000_AddPlayerProfileImages")]
    partial class AddPlayerProfileImages
    {
    }
}
