// <auto-generated />
using DatabaseEntities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MigrationHandler.Migrations
{
    [DbContext(typeof(App_DBContext))]
    [Migration("20260603090000_AddPlayerProfiles")]
    partial class AddPlayerProfiles
    {
    }
}
