// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DatabaseEntities;

public partial class App_DBContext : DbContext
{
    public App_DBContext(DbContextOptions<App_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ErrError> ErrErrors { get; set; }

    public virtual DbSet<LogAdmin> LogAdmins { get; set; }

    public virtual DbSet<LogBaccarat> LogBaccarats { get; set; }

    public virtual DbSet<LogBlackjack> LogBlackjacks { get; set; }

    public virtual DbSet<LogHorse> LogHorses { get; set; }

    public virtual DbSet<LogRoulette> LogRoulettes { get; set; }

    public virtual DbSet<LogSpin> LogSpins { get; set; }

    public virtual DbSet<UsrAdmin> UsrAdmins { get; set; }

    public virtual DbSet<UsrPlayer> UsrPlayers { get; set; }

    public virtual DbSet<UsrSession> UsrSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ErrError>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_ERR_Error");

            entity.ToTable("ERR_Error");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Date).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Host).HasMaxLength(255);
            entity.Property(e => e.Uri).HasMaxLength(500);
        });

        modelBuilder.Entity<LogAdmin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_LOG_Admin");

            entity.ToTable("LOG_Admin");

            entity.HasIndex(e => new { e.AdminId, e.CreatedAt }, "idx_LOG_Admin_Time");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Action).HasMaxLength(30);
            entity.Property(e => e.AdminId).HasColumnName("AdminID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Detail).HasMaxLength(255);
            entity.Property(e => e.TargetId).HasColumnName("TargetID");

            entity.HasOne(d => d.Admin).WithMany(p => p.LogAdmins)
                .HasForeignKey(d => d.AdminId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_LOG_Admin_Admin");
        });

        modelBuilder.Entity<LogBaccarat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_LOG_Baccarat");

            entity.ToTable("LOG_Baccarat");

            entity.HasIndex(e => new { e.PlayerId, e.CreatedAt }, "idx_LOG_Baccarat_PlayerTime");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BankerHand).HasMaxLength(60);
            entity.Property(e => e.BetType).HasMaxLength(10);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Outcome).HasMaxLength(10);
            entity.Property(e => e.PlayerHand).HasMaxLength(60);
            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");

            entity.HasOne(d => d.Player).WithMany(p => p.LogBaccarats)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("fk_LOG_Baccarat_Player");
        });

        modelBuilder.Entity<LogBlackjack>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_LOG_Blackjack");

            entity.ToTable("LOG_Blackjack");

            entity.HasIndex(e => new { e.PlayerId, e.CreatedAt }, "idx_LOG_Blackjack_PlayerTime");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.DealerCards).HasMaxLength(500);
            entity.Property(e => e.PlayerCards).HasMaxLength(500);
            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");
            entity.Property(e => e.Result).HasMaxLength(15);

            entity.HasOne(d => d.Player).WithMany(p => p.LogBlackjacks)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("fk_LOG_Blackjack_Player");
        });

        modelBuilder.Entity<LogHorse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_LOG_Horse");

            entity.ToTable("LOG_Horse");

            entity.HasIndex(e => new { e.PlayerId, e.CreatedAt }, "idx_LOG_Horse_PlayerTime");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.PickedName).HasMaxLength(30);
            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");
            entity.Property(e => e.WinnerName).HasMaxLength(30);

            entity.HasOne(d => d.Player).WithMany(p => p.LogHorses)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("fk_LOG_Horse_Player");
        });

        modelBuilder.Entity<LogRoulette>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_LOG_Roulette");

            entity.ToTable("LOG_Roulette");

            entity.HasIndex(e => new { e.PlayerId, e.CreatedAt }, "idx_LOG_Roulette_PlayerTime");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");
            entity.Property(e => e.WinNum).HasMaxLength(3);

            entity.HasOne(d => d.Player).WithMany(p => p.LogRoulettes)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("fk_LOG_Roulette_Player");
        });

        modelBuilder.Entity<LogSpin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_LOG_Spin");

            entity.ToTable("LOG_Spin");

            entity.HasIndex(e => new { e.PlayerId, e.CreatedAt }, "idx_LOG_Spin_PlayerTime");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");
            entity.Property(e => e.SpinType).HasMaxLength(10);
            entity.Property(e => e.Symbols).HasMaxLength(40);

            entity.HasOne(d => d.Player).WithMany(p => p.LogSpins)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("fk_LOG_Spin_Player");
        });

        modelBuilder.Entity<UsrAdmin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_USR_Admins");

            entity.ToTable("USR_Admins");

            entity.HasIndex(e => e.Email, "uq_USR_Admins_Email").IsUnique();

            entity.HasIndex(e => e.Username, "uq_USR_Admins_Username").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Email).HasMaxLength(254);
            entity.Property(e => e.PasswordHash).HasMaxLength(60);
            entity.Property(e => e.Username).HasMaxLength(40);
        });

        modelBuilder.Entity<UsrPlayer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_USR_Players");

            entity.ToTable("USR_Players");

            entity.HasIndex(e => e.Email, "uq_USR_Players_Email").IsUnique();

            entity.HasIndex(e => e.Name, "uq_USR_Players_Name").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Email).HasMaxLength(254);
            entity.Property(e => e.Name).HasMaxLength(20);
            entity.Property(e => e.PasswordHash).HasMaxLength(60);
        });

        modelBuilder.Entity<UsrSession>(entity =>
        {
            entity.HasKey(e => e.Token).HasName("pk_USR_Sessions");

            entity.ToTable("USR_Sessions");

            entity.HasIndex(e => e.PlayerId, "idx_USR_Sessions_Player");

            entity.Property(e => e.Token).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.PlayerId).HasColumnName("PlayerID");

            entity.HasOne(d => d.Player).WithMany(p => p.UsrSessions)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("fk_USR_Sessions_Player");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}