// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class ErrError
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string Exception { get; set; } = null!;

    public string Message { get; set; } = null!;

    public string Uri { get; set; } = null!;

    public string Host { get; set; } = null!;
}