// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class LogAdmin
{
    public long Id { get; set; }

    public int AdminId { get; set; }

    public string Action { get; set; } = null!;

    public Guid? TargetId { get; set; }

    public string? Detail { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UsrAdmin Admin { get; set; } = null!;
}