// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class LogBaccarat
{
    public long Id { get; set; }

    public Guid PlayerId { get; set; }

    public string BetType { get; set; } = null!;

    public string Outcome { get; set; } = null!;

    public string PlayerHand { get; set; } = null!;

    public string BankerHand { get; set; } = null!;

    public int Bet { get; set; }

    public int Net { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UsrPlayer Player { get; set; } = null!;
}