// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class LogRoulette
{
    public long Id { get; set; }

    public Guid PlayerId { get; set; }

    public string WinNum { get; set; } = null!;

    public int TotalBet { get; set; }

    public int Net { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UsrPlayer Player { get; set; } = null!;
}