// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class LogSpin
{
    public long Id { get; set; }

    public Guid PlayerId { get; set; }

    public byte MachineNum { get; set; }

    public string Symbols { get; set; } = null!;

    public int Bet { get; set; }

    public int WinAmount { get; set; }

    public string SpinType { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public virtual UsrPlayer Player { get; set; } = null!;
}