// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class UsrPlayer
{
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string PasswordHash { get; set; } = null!;

    public int Tokens { get; set; }

    public DateTime? LastBonusAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<LogBaccarat> LogBaccarats { get; set; } = new List<LogBaccarat>();

    public virtual ICollection<LogBlackjack> LogBlackjacks { get; set; } = new List<LogBlackjack>();

    public virtual ICollection<LogHorse> LogHorses { get; set; } = new List<LogHorse>();

    public virtual ICollection<LogRoulette> LogRoulettes { get; set; } = new List<LogRoulette>();

    public virtual ICollection<LogSpin> LogSpins { get; set; } = new List<LogSpin>();

    public virtual ICollection<UsrSession> UsrSessions { get; set; } = new List<UsrSession>();
}