// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DatabaseEntities;

public partial class UsrSession
{
    public Guid Token { get; set; }

    public Guid PlayerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UsrPlayer Player { get; set; } = null!;
}